### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by Midar** [ianpatt/skse64#45]
Would it be able to add Linux support via Proton Experimental? Right now all it does is show a tiny black window and exit immediately. The log doesn't say more than this:

```
skse64 loader 02020060 01DB1D9103DBFD20 6.2 (9200)
config path = Z:\home\js\.var\app\com.valvesoftware.Steam\.local\share\Steam\steamapps\common\Skyrim Special Edition\Data\SKSE\skse.ini
procPath = Z:\home\js\.var\app\com.valvesoftware.Steam\.local\share\Steam\steamapps\common\Skyrim Special Edition\\SkyrimSE.exe
launching: SkyrimSE.exe (Z:\home\js\.var\app\com.valvesoftware.Steam\.local\share\Steam\steamapps\common\Skyrim Special Edition\\SkyrimSE.exe)
dwSignature = FEEF04BD
dwStrucVersion = 00010000
dwFileVersionMS = 00010006
dwFileVersionLS = 04920000
dwProductVersionMS = 00010006
dwProductVersionLS = 04920000
dwFileFlagsMask = 00000017
dwFileFlags = 00000000
dwFileOS = 00000004
dwFileType = 00000001
dwFileSubtype = 00000000
dwFileDateMS = 00000000
dwFileDateLS = 00000000
productVersionStr = 1.6.1170.0
version = 0001000604920000
product name = TESV: Skyrim
steam exe
dll = Z:\home\js\.var\app\com.valvesoftware.Steam\.local\share\Steam\steamapps\common\Skyrim Special Edition\\skse64_1_6_1170.dll
main thread id = 380
hookBase = 0000000000140000
loadLibraryAAddr = 00006FFFFFECEB88
getProcAddressAddr = 00006FFFFFED0940
hook thread complete
launching
```

Are there any other log files that might be useful? (This is the only log file that I can find using `find .var/app/com.valvesoftware.Steam -iname '*skse*'`)

**Comment by ianpatt** [comment]
As far as I know, SKSE has worked in Proton for quite a long time now. There was a bug forever ago that would only show up due to Proton/WINE's inaccurate simulation of Windows, but it was fixed. That log file shows a successful process startup and injection from the loader's perspective, so for the moment I can only assume that the problem is on the Proton/WINE side or user error.

I can't give general technical support for Proton/WINE, but can give engineering support if someone familiar with building and debugging Proton is looking at the issue.

**Comment by ianpatt** [comment]
As [noted in ProtonDB](https://www.protondb.com/app/489830) it is currently working.

**Comment by Midar** [comment]
I tried with Proton 8 as well as with Proton Experimental and it's the same with both :/

**Comment by ianpatt** [comment]
As mentioned, I cannot provide technical support for Proton or WINE.
